version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
  frontend:
    image: nginx
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 8080:80
